// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe5obwcQXpTSM-VqR5KrD7Fz8Cf6ex7fI',
    appId: '1:908004485129:web:79bfd262248a39a5edb0d8',
    messagingSenderId: '908004485129',
    projectId: 'demoapplication-5b98d',
    authDomain: 'demoapplication-5b98d.firebaseapp.com',
    storageBucket: 'demoapplication-5b98d.firebasestorage.app',
    measurementId: 'G-QSMNJ67PC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVbt-0iCEwc-Zg0F483_gyHMSQHvM1vNw',
    appId: '1:908004485129:android:25e97f0d75f1b07cedb0d8',
    messagingSenderId: '908004485129',
    projectId: 'demoapplication-5b98d',
    storageBucket: 'demoapplication-5b98d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH018c-UNzsoidnWs8dY5hjnkLKoDCTzo',
    appId: '1:908004485129:ios:9723ea22a283157dedb0d8',
    messagingSenderId: '908004485129',
    projectId: 'demoapplication-5b98d',
    storageBucket: 'demoapplication-5b98d.firebasestorage.app',
    iosBundleId: 'com.example.demoApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH018c-UNzsoidnWs8dY5hjnkLKoDCTzo',
    appId: '1:908004485129:ios:9723ea22a283157dedb0d8',
    messagingSenderId: '908004485129',
    projectId: 'demoapplication-5b98d',
    storageBucket: 'demoapplication-5b98d.firebasestorage.app',
    iosBundleId: 'com.example.demoApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe5obwcQXpTSM-VqR5KrD7Fz8Cf6ex7fI',
    appId: '1:908004485129:web:5d18ce9fc40148f6edb0d8',
    messagingSenderId: '908004485129',
    projectId: 'demoapplication-5b98d',
    authDomain: 'demoapplication-5b98d.firebaseapp.com',
    storageBucket: 'demoapplication-5b98d.firebasestorage.app',
    measurementId: 'G-37HNY05XV4',
  );
}
